Algoritmo "logico"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Larissa
// Data atual  : 27/08/2022
Var
// Seção de Declarações das variáveis 


Inicio
          se (1 = (2 -1)) e (2 = (1 + 1)) entao
          Escreval("Ambas as expressões são verdadeiras")
          fimse
          
          se (1 <> (2 -1)) ou (2 = (1 + 1)) entao
          Escreval("iguais")
          fimse

Fimalgoritmo