Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2022
Var
texto: caractere


Inicio
texto<- "TESTE"

      se texto = "TESTE" entao
      escreval(texto , " igual")
      fimse

Fimalgoritmo